### ISSUE TITLE
Determine the sender of a mail

### ISSUE THREAD

**Issue by TobiSonne** [enricoschumann/mailtools#1]
Hi Enrico, 

a colleague and I sent hundreds of personalized emails via Outlook today using your package and it worked wonderfully. We definitely will use it in the future, too. Especially the possibility with display.only was very helpful to be able to check everything besore sending. We had to send the e-mails from the Secretariat's account, but were primarily logged in with a personal account, so we had to specify for each e-mail, from which address it was sent. Do you think you could add an option that determines the sender? That would be great.

Best wishes,
Tobi

**Comment by enricoschumann** [comment]
Hi Tobi,

I can look into this. Is the email really sent via a
different account, or by only adding a "on behalf of"
("im Namen von") header?

**Comment by TobiSonne** [comment]
Great, thank you!
We only had "Von", see here:
https://support.office.com/de-de/article/senden-von-e-mails-%C3%BCber-eine-andere-adresse-in-outlook-com-ccba89cb-141c-4a36-8c56-6d16a8556d2e

**Comment by enricoschumann** [comment]
OK, I did look into it. Whether you can choose an account will depend on your setup: whether you use an exchange server, what rights the admin has given you, ... As I said before, I cannot test on Windows. So could you try the following PowerShell-Script on Windows with an Outlook that has several accounts?

    $o = New-Object -com Outlook.Application;

    foreach ($a in $o.Session.Accounts) {
        write-host $a.username;

        $mail = $o.CreateItem(0);
        $mail.To = "testing@testing.net"
        $mail.SendUsingAccount = $a;
        $mail.Display();
    }
 
It should loop through all accounts that you can access and create messages with different accounts. (If you can, perhaps really use a real e-mail-address and use ```$mail.Send()``` in the last line.) Let me know if that actually sets the account.

**Comment by TobiSonne** [comment]
Thank you so far! I will test it next week at work and let you know!

**Comment by TobiSonne** [comment]
`write-host $a.username` prints all the accounts (without domain) as expected.
But unfortunately the opened mails always have the same account in "Von" (the default account).
I also tried `"$mail.SendUsingAccount = $a.username;"` and `$mail.SendUsingAccount = "myrealaccount";` with the account that I wished to send the mail from (with and without domain) but nothing happens.

**Comment by enricoschumann** [comment]
Too bad; the documentation made me believe it should work.
How about this? If it works, could you try to actually send an email and see how it arrives?

    $o = New-Object -com Outlook.Application;
    $mail = $o.CreateItem(0);
    $mail.To = "testing@testing.net"
    $mail.Subject = "Test";
    $mail.SentOnBehalfOfName = "myacocunt@testing.net";  ## your actual account
    $mail.Display();     ##  $mail.Send() to actually send the email

**Comment by TobiSonne** [comment]
Yes, really strange, that must be the correct way ... Perhaps a bug?
I also tried SentOnBehalfOfName on Monday but it leads to "Sonne, Tobias <sonne@blabla.de>; im Auftrag von; t_sonne@gmx.de" as sender and the mail is from my account (sonne@blabla.de) and not the one from which I want to send it (t_sonne@gmx.de).

**Comment by enricoschumann** [comment]
MS does not produce bugs, only very particular features :-) Apparently, judging from what I have seen in some help forums, quite a few people have the same problem (some claim that ```SendUsingAccount``` worked prior to PowerShell 5). So right now I am out of ideas; sorry.

**Comment by TobiSonne** [comment]
Yes, I've seen some discussions online ...
Thank you anyway!

**Comment by enricoschumann** [comment]
OK, let's give it a final try. I just pushed an updated version of ```mailtools``` to GitHub. With this new version, could try the following code:

```
library("mailtools")

sendmail(subject = "Test",
         body = "Test",
         to = "testor@testing.net",
         method = "outlook",         
         display.only = TRUE,
         SendUsingAccount = "alternative@testing.net")
```
(Btw, you may want to delete the email addresses in your post, or change them to dummy addresses.)

**Comment by TobiSonne** [comment]
WORKS!! Thank you so much!
Btw: Your function inspired me to use the command line via R, I've already created some useful functions with the help of that.
The email addresses are fake, these are not mine.
