### ISSUE TITLE
Default value of SendUsingAccount

### ISSUE THREAD

**Issue by TobiSonne** [enricoschumann/mailtools#2]
I wanted to use your function again and wanted to write the mail from my main account, so I didn't specify the argument SendUsingAccount. If you do so you get the error message `object 'l1' not found`. This is caused by `l1 <- paste0("$acc = $o.Session.Accounts | ", 
                  "Where-Object { $_.SmtpAddress -eq ", shQuote(SendUsingAccount), 
                  " }")`
If I do not specify `SendUsingAccount` `l1` cannot be created. So I have to write my own email in that parameter. Could you fix that so that you do not need to specify this?
Thank you very much!

**Comment by enricoschumann** [comment]
Many thanks for the report.  I have pushed an updated
version.  Could you try it, please?

**Comment by TobiSonne** [comment]
Works!
Thank you very much for the fast fix!
